/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_platinumforge_studio_jni_fibonacci_FibLib */

#ifndef _Included_com_platinumforge_studio_jni_fibonacci_FibLib
#define _Included_com_platinumforge_studio_jni_fibonacci_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_platinumforge_studio_jni_fibonacci_FibLib
 * Method:    fibNR
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_platinumforge_studio_jni_1fibonacci_FibLib_fibNR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_platinumforge_studio_jni_fibonacci_FibLib
 * Method:    fibNI
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_platinumforge_studio_jni_1fibonacci_FibLib_fibNI
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
