/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_platinumforge_studio_jni_fibonacci_FibLib.h"

    static jlong fib (jlong n)
    {
        return n <=0 ? 0 : n == 1 ? 1 : fib(n-1) + fib(n-2);
    }

JNIEXPORT jlong JNICALL Java_com_platinumforge_studio_jni_1fibonacci_FibLib_fibNR
  (JNIEnv *env, jclass clazz, jlong n)
  {
    return fib(n);
  }


JNIEXPORT jlong JNICALL Java_com_platinumforge_studio_jni_1fibonacci_FibLib_fibNI
  (JNIEnv *env, jclass clazz, jlong n)
  {
          jlong previous = -1;
          jlong result = 1;
          jlong i;
          for (i=0; i<n; i++)
          {
              jlong sum = result + previous;
              previous = result;
              result = sum;
          }
          return result;
  }
